version: 2.0.{build}
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '2.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'

build:
  verbosity: minimal

test:

after_test:
  - cmd: dotnet run --project test\Paramore.Darker.Benchmarks\Paramore.Darker.Benchmarks.csproj --configuration %CONFIGURATION%

artifacts:
  - path: '**\*.nupkg'
  - path: BenchmarkDotNet.Artifacts\results\*

deploy:
  provider: NuGet
  api_key:
    secure: mYg+TXuLQs9C2GPJj26Cjy7MFWJcN1p5C5/n0ksQIvL7a14QcLGX09CUU7Hlq8hM
  on:
    appveyor_repo_tag: true
