version: '{build}'
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

install:
  - ps: Import-Module .\Set-Version.psm1
  - ps: Set-Version -Path "src\Paramore.Darker\Paramore.Darker.csproj" -SetAppveyorVersion
  - ps: Set-Version -Path "src\Paramore.Darker.AspNetCore\Paramore.Darker.AspNetCore.csproj"
  - ps: Set-Version -Path "src\Paramore.Darker.QueryLogging\Paramore.Darker.QueryLogging.csproj"
  - ps: Set-Version -Path "src\Paramore.Darker.Policies\Paramore.Darker.Policies.csproj"
  - ps: Set-Version -Path "src\Paramore.Darker.LightInject\Paramore.Darker.LightInject.csproj"
  - ps: Set-Version -Path "src\Paramore.Darker.SimpleInjector\Paramore.Darker.SimpleInjector.csproj"
  - ps: Set-Version -Path "src\Paramore.Darker.Testing\Paramore.Darker.Testing.csproj"

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\Paramore.Darker --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.AspNetCore --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.QueryLogging --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.Policies --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.LightInject --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.SimpleInjector --configuration %CONFIGURATION% --no-build --output ..\..\artifacts
  - cmd: dotnet pack src\Paramore.Darker.Testing --configuration %CONFIGURATION% --no-build --output ..\..\artifacts

test_script:
  - cmd: dotnet test test\Paramore.Darker.Tests\Paramore.Darker.Tests.csproj
  - cmd: dotnet run --project test\Paramore.Darker.Benchmarks\Paramore.Darker.Benchmarks.csproj --configuration %CONFIGURATION%

artifacts:
  - path: artifacts\*.nupkg
  - path: BenchmarkDotNet.Artifacts\results\*

deploy:
  provider: NuGet
  api_key:
    secure: mYg+TXuLQs9C2GPJj26Cjy7MFWJcN1p5C5/n0ksQIvL7a14QcLGX09CUU7Hlq8hM
  on:
    appveyor_repo_tag: true