version: '{build}'
configuration: Release

install:
  - ps: Invoke-WebRequest -Uri "https://gist.githubusercontent.com/dstockhammer/e5b8858c9318db7970532cc35f520294/raw/Set-ProjectVersion.psm1" -OutFile "Set-ProjectVersion.psm1"
  - ps: Import-Module .\Set-ProjectVersion.psm1
  - ps: Set-ProjectVersion -Path "src\Darker\project.json" -SetAppveyorVersion
  - ps: Set-ProjectVersion -Path "src\Darker.Serialization.NewtonsoftJson\project.json"
  - ps: Set-ProjectVersion -Path "src\Darker.LightInject\project.json"

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build */*/project.json --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\Darker --configuration %CONFIGURATION% --output artifacts
  - cmd: dotnet pack src\Darker.Serialization.NewtonsoftJson --configuration %CONFIGURATION% --output artifacts
  - cmd: dotnet pack src\Darker.LightInject --configuration %CONFIGURATION% --output artifacts

test_script:
  - cmd: dotnet test test\Darker.Tests

artifacts:
  - path: artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: NLJUBg6WGLN/c7rADEe50wdSE+DwN0XKzPGz5iFbYkVtT3bwSyYuKuZbcGb75xM2
