version: '{build}'
configuration: Release

install:
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
  - ps: ./dotnet-install.ps1 -Version 1.0.0-rc4-004771
  - ps: Import-Module .\Set-Version.psm1
  - ps: Set-Version -Path "src\Darker\Darker.csproj" -SetAppveyorVersion
  - ps: Set-Version -Path "src\Darker.RequestLogging\Darker.RequestLogging.csproj"
  - ps: Set-Version -Path "src\Darker.Policies\Darker.Policies.csproj"
  - ps: Set-Version -Path "src\Darker.LightInject\Darker.LightInject.csproj"
  - ps: Set-Version -Path "src\Darker.SimpleInjector\Darker.SimpleInjector.csproj"
  - ps: Set-Version -Path "src\Darker.Testing\Darker.Testing.csproj"

build_script:
  - cmd: set DOTNET_CLI_TELEMETRY_OPTOUT=1
  - cmd: dotnet restore
  - cmd: dotnet build --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\Darker --configuration %CONFIGURATION% --output ..\..\artifacts
  - cmd: dotnet pack src\Darker.RequestLogging --configuration %CONFIGURATION% --output ..\..\artifacts
  - cmd: dotnet pack src\Darker.Policies --configuration %CONFIGURATION% --output ..\..\artifacts
  - cmd: dotnet pack src\Darker.LightInject --configuration %CONFIGURATION% --output ..\..\artifacts
  - cmd: dotnet pack src\Darker.SimpleInjector --configuration %CONFIGURATION% --output ..\..\artifacts
  - cmd: dotnet pack src\Darker.Testing --configuration %CONFIGURATION% --output ..\..\artifacts

test_script:
  - cmd: dotnet test test\Darker.Tests\Darker.Tests.csproj
  - cmd: dotnet run --project test\Darker.Benchmarks\Darker.Benchmarks.csproj --configuration %CONFIGURATION%

artifacts:
  - path: artifacts\*.nupkg
  - path: BenchmarkDotNet.Artifacts\results\*

deploy:
  provider: NuGet
  api_key:
    secure: mYg+TXuLQs9C2GPJj26Cjy7MFWJcN1p5C5/n0ksQIvL7a14QcLGX09CUU7Hlq8hM
