version: '{build}'
configuration: Release

install:
  - ps: >-
      $projectJsonPath = "src\Darker\project.json"

      $str = Get-Content -Raw -Path $projectJsonPath

      $json = ConvertFrom-Json $str

      $version = $buildVersion = $json.version

      if ($env:APPVEYOR_REPO_TAG -eq $false) {
        $buildVersion = "$version-ci$($env:APPVEYOR_BUILD_NUMBER)"

        $str.Replace($"""version"": ""$version"",", $"""version"": ""$buildVersion"",") | Set-Content $projectJsonPath
      }

      Update-AppveyorBuild -Version $buildVersion

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build */*/project.json --configuration %CONFIGURATION%

test_script:
  - cmd: dotnet test test\Darker.Tests

on_success:
  - cmd: dotnet pack src\Darker --configuration %CONFIGURATION% --output artifacts

on_finish:
  - ps: Get-ChildItem .\artifacts\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
